### ISSUE TITLE
[BUG] Text alignment

### ISSUE THREAD

**Issue by Retacky** [lukasbach/yana#6] opened 2020-12-02 11:01 UTC
**Describe the bug**
When I try to align a text, nothing happens

**To Reproduce**
1. create any note item
2. type any text
3. open the alignment option and click on any 3's

**Expected behavior**
Text alignment to left, right or center

**Screenshots**
![image](https://user-images.githubusercontent.com/62518118/100864149-5d3c0f80-3474-11eb-8b96-cc203c1fee8f.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Yana Version: 1.0.4

**Comment by lukasbach** [comment] 2020-12-02 11:36
Hi Retacky, thank you for your report. Issue can be reproduced, I will fix it in the next version.

**Comment by lukasbach** [comment] 2020-12-03 16:50
Unfortunately, this issue seems to be caused by dependencies (``@atlaskit/editor-core`` and ``prosemirror-state``). Due to breaking changes, upgrading them is a bigger task which likely is not going to make it into the next version.

**Comment by kepta** [comment] 2021-03-28 02:01
I have been working on https://bangle.dev which is inspired by atlaskit maybe we can work together to help you unblock your app?

**Comment by lukasbach** [comment] 2021-03-29 11:23
Hi @kepta. Does bangle.dev internally use atlaskit? What is your plan for unblocking?

Awesome project btw :)

**Comment by kepta** [comment] 2021-03-29 14:33
It uses Prosemirror which is what atlaskit also uses. By unlocking I meant
use text alignment.

**Comment by lukasbach** [comment] 2021-04-13 22:31
@kepta the issue was more about cross dependencies between atlaskit and less about prosemirror itself. Anyway, I've went through and cleared the dependency issues, so this issue will be fixed in the next release of yana.

However, there is another reason why I think bangle might be interesting to yana. Atlaskit doesnt support any markdown deserialization, but that seems to be on the roadmap for bangle. I don't want to replace Atlaskit, but I could imagine adding bangle editor for an additional "Markdown note type" the same way that yana currently supports code-notes with Monaco editor and todo lists with a custom implementation.

Am I correct that bangle currently doesn't support exporting note contents to Markdown, but that it's planned? I saw a ``@bangle.dev/markdown`` package, but no documentation yet. If so, do you have plannes when to ship that feature?

**Comment by kepta** [comment] 2021-04-13 23:45
Bangle.dev has first party support for markdown. Unfortunately I haven't gotten the time to update the api documentation. I have an example which demonstrates serialization and parsing https://bangle.dev/docs/examples/markdown-editor . Using that and browsing the code you should be able to get an excellent markdown support. Also happy to accept PR to improve the api doc.

**Comment by lukasbach** [comment] 2021-04-14 00:15
Oh, okay, that sounds great! I'll work on integrating bangle.dev as Markdown editor to yana (#25). 

Coming back to the original reason this issue was opened - the issue is fixed in Yana 1.0.10, text alignments should now work as intended.

**Closed** 2021-04-14 00:15 UTC
Labels: bug
